# Created alpine images
FROM alpine:latest
# Created non-default bridge network

# WORKDIR /home/root/

# Run these containers in non-default bridge network
# docker run --network=for_hm --expose=80 -v=$(pwd):/home/root -d --name cont1 alpine
# docker run --network=for_hm -v=$(pwd):/home/root -d alpine

# docker run -d --network=for_hm cont1

# CMD ["sh", "server/server.sh"]