# Created alpine images
FROM alpine:latest
# WORKDIR /root/

# Created non-default bridge network
# RUN docker network create for_hm

# WORKDIR /home/root/



# Run these containers in non-default bridge network
# docker run --network=for_hm --expose=80 -v=$(pwd):/home/root -d --name cont1 alpine
# docker run --network=for_hm -v=$(pwd):/home/root -d alpine

# docker run -d --network=for_hm cont1

# CMD ["sh", "script"]